(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"Website_atlas_1", frames: [[0,0,1280,720]]}
];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.StreamIntro24fps1080_0 = function() {
	this.initialize(ss["Website_atlas_1"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Symbol2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("A3tKaIgEgBIgFgDIgDgDIgEgEIgCgGIgCgFIgIh6QgEg6gJg5QgKg7gFg7QgGg6gCg7QgDg8AFg8QAAgLAFgKIACgEIACgDIADgFIAEgEIAFgEIAFgDIAFgDIAFgDIAGgCIAGAAIAHAAIAFAAIAGAAIAFACIAGACQArAcAaAuQAYArAUAuQAWAzAUAzQASAvARAxQARAzAXAxQAHAPAJAOIADAEIADAEIAEAEIADAFIADAFIACAFIACAGIABAFIAAAGIAAAGIgBAGIgCAGIgCAFIgDAFIgDAEIgEAFIgIAGIgJAEIgKADIgKACIgKgBIgFgBIgFgCIgEgCIgFgCIgEgEQgggggQgqQgPglgNglIgPAFIgSAHIgRAHIgPAHIgNADIgFAAIgCAAIgDAAQACApAAAnQAAAugDAtIgBAPIgCAEIgDAGIgDAEIgEADIgEADIgFABIgFAAIgFAAgA3aEKQACAsAEAsIAFA3IAOgLIAQgKIAVgLIASgIIABgBIgIgZIgfhTQgQgogRgnIgJgSQgBAzABA0gAtLJkIgEgBIgEgCIgEgBIgEgEIgEgDIgCgEIgDgFIgBgGIAAgFIABgFIADgGIACgEIAEgDIAEgEIAFgBIAWgHIAZgKIASgJIAXgNIAMgHIAFgFIAFgEIAFgGIAFgEIAEgGIAFgEQAggrAOgzQANgvgCgyQgBgogKgmQgLgmgSgjQgIgPgKgOIgFgFIgEgGIgFgFIgFgFIgFgEIgFgEIgFgDIgGgCIgDgBIgEgCIgGgCIgFgCIgFgEIgFgDIgFgEIgDgFIgEgFIgDgGIgCgFIgBgGIgBgGIAAgHIAAgFIACgHQAgg9A/AmQBUAyAhBeQAeBVgDBaQgEBkgzBWQg+Bph5ARIgSABIgTgBgAx8ISQgjgEgagbQgYgZgQggQgOgdgMgdQgNghgIgiQgIggAGghQACgJAEgJIADgEIADgEIAEgCIAFgCIAEgCIAFgBIAFAAIAFACIAGACIAEACIAFAFIADAEIADAGIABAFIAAAGIgBAHIAAACIAAAGIAAAFQADARAGAQIAMAgIACAFIAQAgQAHAPAJAPIAPAWIAFAFIAEAFIABgFIABgHQACgegCgeQgCgegDgeIgIg1IgGgtIgCgNIAAgGIABgHIACgGIADgGIADgFIAEgDIAEgEIAEgDIAFgDIAEgDIAGgCIAGgBIAGAAIAHAAIAGABIAGACIAGAEIAEADIAFADIADAEIAEAEIADAFIACAEQAIAnAFAnQAGAnADApQADAggBAhQgBAfgHAeQgFAUgLASIgEAFIgDAEIgEAFIgEADIgEADIgEAEIgFACIgFACIgFACIgFADIgFABIgGAAIgGABIgFAAgAvMGmIgGgBIgHgBIgGgDIgHgDIgFgCIgFgDIgEgDIgGgHIgFgJIgEgJIgCgJIAAgKIABgKIACgFIADgGIADgFIADgEIAEgEIAFgEIAFgDIAFgDIAGgCIAGgCIAGAAIAGAAIAGAAQALgCAJgFIASgJIASgJIARgLIAFgFIAFgEIADgGIADgFIACgFIABgFIAAgFQgYgGgZgFQgWgFgVgJQgRgIgOgMQgMgKgHgOQgFgIgCgIIgBgFIgBgGIAAgEIAAgHIABgGIABgGIABgGQAJgYASgQQATgRAVgNQAVgLAXgGQASgEASACQAUACASAEIAFACIAEADIAEAEIADADIACAFIACAEIAAAGIAAAFIgCAFIgCAFIgEADIgEAEIgEADIgFABIgGABIgGgBIgHAAIgHAAIgGgBIgFABIgGAAIgFABIgFABIgFACIgFADIgEACIgFADIgGAEIgEAEIgFAEIgFAEIgEAFIgEAEIgFAGIgCADIAAAAIAGAEIAFADQAaAJAbADQAaACAXALQASAIANAPQALAOAEARQAEAOAAAPQAAAigQAeQgOAYgVASQgUARgXAOQgTALgVAJQgPAHgPAFIgGACIgHABIgHABIgEAAgAm5C2QgzgFgqgfQgqgegHg0QgHgxAdgoQAcgoAigiQAkgmAygIQAIgBAIACQAXAFAOAUQAQAWALAaQAMAaAOAZQAPAZASAXQAPAVASARIAOANIAFAEIAGAEIAFADIAGADIAGAEIAGACIASAHIAUAEQAKADALABQALABALAAIAOAAIAHABIAFABIAEADIAEAEIADAEIADAGIAAAHIAAAFIgDAHIgCAEIgEADIgEACQgOALgRAEQgYAGgZgCQgYAAgXgHQgWgGgTgKQgVgLgSgPQgIADgLAJQgMAKgOAHQgNAHgPAGQgPAFgQACIgbACIgSgBgAmsgXIgJAIIgIAJIgOAOQgGAHgFAJIgIALIgDAGIgBAHIAAADIAAABIAEADIADAEIAEADIAFADIAGAEIAGACIAGACIAGACIAGACIAHAAIAHAAIAHAAIAHgCIAHgCIAGgCIAGgDIAGgEIAGgDIAGgEIAFgEIgGgIIgHgKIgMgRIgLgSIgLgSIgHgNIgIAIgAgLCuIAAAAIgFgCIgFgBIgFgCIgFgEQghgggQgsIgWg/QgKgfgEghQgEgfAAgfQABgcANgZIAJgLIAEgFIAGgDQAHgFAIgDQALgCALACQAUADAQANIAOAMIALAOIANAPQAEgYAKgVQAEgIAGgGQAGgHAHgFIAJgHQAwgUAoAiQAZAXAQAcQAQAcAMAdQAOAhAJAiQAIAbAKAdIACAGIABAGIABAHIgBAHIgBAHIgCAFIgCAGIgDAEIgEAFIgEAEIgEAEQgMAJgOABIgJAAIgJgCIgIgDIgIgEIgHgGIgGgHQgPgcgIgfQgEgVgGgTIgMghQgGgQgIgPIgDgGQgFAcgCAdIgBAZIgCAaQAAAIgDAIIgCAFIgDAGQgGAIgIAGIgEAEIgFACIgFABQgKADgKgCIgFgBIgFgBIgFgBIgEgDIgEgDQgGgGgFgIQgIgRgGgSIgJgXIgMgZIgNgXIgHgMQAAAkAJAiIAKAoIAMAnQAGARAJARIAJANIACAFIABAEIABAGIgBAEIgCAFIgBADIgDAEIgDADIgEACIgFACIgFABIgHgBgAAAAOIAAAAIAAgBgAGjBsQg/gHgtguQgugvgRg9QgRg+Adg5QAcg3AzgkQA3goBCAKQAJABAIAEIAFADIAFAEIAFADIACADIADAEIABADIAAAEIAAADIAAAEIgCAEIgBADIgDADIgCADIgDABIgEACIgDABIgEAAIgHAAIgHAAIgHABIgHACIgGACIgGACIgGABQgLAGgKAFQgKAHgJAHIgRAQIgQASQgHAIgGALIgJAOIgCAFIgBAGIgCAFIAAAHIAAAGIAAAGIAAAHIAFATQADAKAEAIIAJAQQAEAHAGAGQAFAIAHAGIAJAJIAGADIAFAEIAFACIAGACIAFADIAFABIAGABIAGAAIAGAAIAHAAIAFgBIAGgBIAGgCIAGgCIALgEIALgHIAMgHIALgHIALgGIALgGIAEgDIAFgCIAFgBIAFgBIAFAAIAFAAIAFAAIAEACIAJAEIAJAFIAEADIAEAEIADAFIACAEIADAGIABAFIABAFIAAAFIAAAFIgBAFIgBAEIgBAFIgCAEIgDAFIgDAEQgMAMgOALIgfAUQgPAJgRAHQgPAGgQADQgTADgTAAIgPAAgAK9AIIgEAAIgEAAIgEgBIgFgBIgEgDIgEgCIgDgBIgDgDQgTgXgNgaQgNgbgMgcIgXg2IgZg2Igbg2IgFgNIgBgGIAAgGIABgFIABgFIACgEIADgDIADgEIAEgCIADgCIAFgCIAEgBIAEAAIAFAAIAFACIAFADIACABIADACQASASANAVIAcAyIAcA1IAdA2QAQAbATAaIAIAMIACAFIABAEIABAEIAAAEIAAAFIgBAFIgBAEIgBAEIgCAEIgCAEIgDADIgDAEIgDADIgEACIgFADIgEABIgFACIgFAAIgFAAgANJhZIgGAAIgFgBQhWgJgchRQgYhCAOhFQAShWBVgOQA8gLAwAmQA+AxAuBCQAWAfAdAaIAEACIAFADIAEADIAFABIAFABIAFABIAFACIAEACIAFACIAEABIAFADIADAEIADADIADAEIABAEIABAFIAAAEIgBAEIgBAFIgDAEIgDAEIgEADIgEADQgNAGgNACQgRACgRgEQgSgFgPgJQgNgJgMgJQgNgLgMgNIgIgJIgKAZQgFANgHANQgIAOgKANQgKALgMAKQgMAHgMAEIgKAFIgFABIgGABIgFAAIgFAAIgGABIgGAAgAM6lEIgDABIgEABIgEACIgCAEIgCADQgFAMgCAMIgCAMIgBAOIgBAOIAAAOIAAAHIACAFIABAFIABAFIACAFIADAGIADADIADACIADADIAEACIAGACIAGABIAFABIAFAAIADgCIADgBIABgBIAGgLIADgEIADgGIAJgYIAFgNIAEgLIAFgNIAGgMIADgFIgFgFIgEgDIgEgFIgFgDIgEgEIgFgCIgFgDIgEgCIgGgCIgFgCIgGgBIgFgBIgFAAIgGAAgAtHh1IgGgBIgHAAIgGgCIgGgEIgFgCIgDgDIgEgEIgDgDIgCgFIgCgDIgCgGIgBgEIgBgFIAAgEIAAgGIABgEIABgGIACgEIADgFIADgFIAEgEIAEgDIAEgEIAFgCIAGgBIABAAIADgBIAFgBIAFAAIAFAAIAFAAIAEACIABAAIAFABIAFADIAEADIAFAEIADAEIAEAFIACAFIACAFIABAGIABAHIAAAFIgBAGIgDAGIgBAEIgCADIgDAFIgDADIgEAEIgEADIgEADIgFACIgEACIgFABIgFAAIgCAAgATAiaIgEgBIgDgCIgEgCIgCgDIgDgDIhHiJQghg/gMhEQgJg8A6gNQAjgIAgAUQA9AmAsA6QAfApAhAoIADAEIABAFIACAEIAAAGIABAFIAAAFIgBAGIgCAEIgCAGIgDAEIgDAFIgDADIgEAEIgFAEIgEACIgFACIgFACIgGABIgFAAIgGgBIgHgBIgEgCIgFgCIgEgCQgRgNgNgRIgWgfIgWgdQgMgQgNgPQgLgOgNgLIgRgPQAGAdAJAbQAHAWAIAVIAQAoIAPApIANAlIAFAOIABAFIAAAFIgBAFIgDAFIgCADIgDADIgEACIgEACIgEAAIgFgBgAXElLIgGAAIgGgBIgEgBIgEgCIgEgCIgDgDIgEgCIgDgDIgCgEIgDgDIgCgFIgCgFIgBgFIgBgFIAAgFIAAgGIACgEIABgEIACgEIACgEIACgEIADgDIADgEIAEgCIAIgEIAJgFIAJgFIAJgGIAEgCQgggVgYgfQgXgcgGgkQgFgiAXgYQAXgYAjgCQAkgCAeAVIADADIADADIADAEIACAEIABAFIABAEIAAAEIAAAEIgBADIgCAFIgCACIgDAEIgDACIgEABIgEABIgEABIgEAAIgEgBIgDgBIgFgBIgFgBIgFAAIgFAAIgFAAIgFAAIgFABIgFABIgFABIgEACIAAAEIABADIABAEIACAEIADAEIACAFIADAEIADAFQAWAZAeAOQAdAOAIAeQAHAYgMAWQgNAWgUARQgXATgaAKIgFACIgGABIgGAAgAHUmsIgHgBIgEgCIgFgBIgDgDIgEgDIgDgDIgCgBIgCgDIgFgEIgEgDIgEgEIgDgEIgCgFIgDgEIgBgGIgBgHIgBgGIAAgGIABgFIABgFIACgFIADgEIACgEIADgEIADgDIAEgDIAGgFIAIgEIAFgCIAFgBIAEAAIAKAAIAIACIAHADIAJAEIADADIAEADIADADIADAFIACADIACAEIACAFIACAEIAAACIADAJQABAHAAAGIgBAKIgCAIIgEAJIgFAHIgEADIgDADIgFADIgDABIgEACIgDABIgGABIgGAAIgGAAgAUoncIgEAAIgEgBIgEgBIgCgCIgDgDIgCgDIgBgCIgCgEIgBgEIgDgeIgBgeIgBgZIgCgZIABgYIAAgIIABgDIABgEIABgDIACgDIACgDIACgDIACgBIADgCIADgDIADgBIAEgBIADgBIAEAAIAEAAIAEABIAEACIADABIAEADIADACIACADIADAEIACADIABAFIABAEIAAADIgEAjIgCAeIgBAYIgBAZIgCAVIgBAFIgBADIgBAEIgCADIgDADIgCADIgDABIgDABIgEABIgDAAg");
	this.shape.setTransform(158.306,66.65);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol2, new cjs.Rectangle(0,0,316.6,133.3), null);


(lib.Symbol1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.StreamIntro24fps1080_0();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol1, new cjs.Rectangle(0,0,1280,720), null);


(lib.StartGame = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(255,255,255,0)").s().p("ATgF8IgOgBQg5gHg4gCIhugEIh1gEQg6gBg5gEQg4gEg4AAQg4AAg4gBQg4gCg4AAQg5gBg6gFQg5gGg4ACIhzADQg6ABg4gCIhugGIhvgFQg5gDg5ABQg4ABg3gDQg5gEg5AAQg4AAg4gCQg6gCg6AAIhuAAIhwAAIhzABQg5AAg4gDQg3gDg4AAQg6ABg6gEQg4gDg4gBQgXAAgXABQg5AEg6gGQgXgCgWAAIAAABIABAAIABABIABAAIACAAIABABIACABIACAAIABABIACAAIACABIACAAIABABIACABIACAAIABAAIABABIABAAIgCAAIgBAAIgDgBIgCgBIgEgBIgDgBIgFgBIgFgBIgFgCIgHgBIgGgDIgGgBIgFgDIgGgCIgFgEIgEgDIgFgEIgDgEIgEgFIgDgFQgIgPgCgRQgEgcgDgcIgEg3IgDg2IgEg4IgEgiIgBgEIAAgDIgEgbIgCgiIgBgmIABgjQABgQAEgQIAFgTIABgHIACgHIABgDIgBgiQAAgPADgOQADgQAJgNQAKgOAQgGQATgJAVAEQASADAPAMQAGAFAFAIQA5gHA5gDIBogHQA7gFA8gBQA6gCA7ADQA1ACA0gBIBtgBIB1gCIB/gBQA6AAA6gCQA4gCA3gEQA2gEA3gBQAbgBAbgCQA0gFA0gHQA4gHA4gBIBrgEQA7gDA6ACQA5ABA6AGQA0AGAyAMQA2ADA2gCQAzgBAzAFIByAIQA7AEA7gCQAzAAAyAFQA1AGA1gBQA5gBA4AFQA5AFA5ADIB3AGQA4ADA5gFQA6gEA6AEQA2AEA3gBQA1AAA1gEQA2gEA1AFQAtADArAMQAJADAHAGQAcAeAJApQAIAoAAAqQgBAugKAsIgTBRQgLAtgGAvQgDAUABAUIACANIABAOIABANIAAANIAAAOIAAAMIgBALIAAAGIgCAGIgCAFIgBAGIgBAFIgCAGIgCAFIgDAGIgDAEIgDAFIgEAEIgEAEIgFADIgFAEIgFADIgFACIgLACIgMADIgNACIgLADIgNACIgNACIgNACIgDAAIhbANIheANQgvAGgvADQgvADgwAAIgNAAQgoAAgogDgA7rk6IAAAAIAAAAgAB+lzIAAAAIABAAg");
	this.shape.setTransform(181.875,30.0754);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(49));

	// Layer_1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AaTEVQg7gHgogvQgngvgLg9QgKg+Agg1QAQgaAWgWQAvgtBCAGQAmADAdAZQAfAgACAqQABAjgQAfQgOAagYAQQgZAQgcAKQgfALghgBIACAEIACAEIAGAGIAHAHIAHAHQAGAHAIAFIAHAFIAFABIAFACIAGABIAEABIAGAAIAFAAIAFgBIAGgBIAFgBIAFgCIAEgCIAFgCIADgCIAFgDIAHgHIAHgIIALgNQAJgIAJgHIAEgDIACgEIADgDIAEgCIADgBIAFgBIABAAIABAAIACAAIAEABIADABIAEACIADADIACADIABAEIAAAFIAAAEIgBAFIgCAEIgEAEIgDAFIAAABIAAAAIgDAEQgMAQgLAQQgLASgPAOQgMALgQAHQgOAHgPACQgNADgNAAIgIgBgAaSgIIgDAAIgEABIgEABIgFADIgDACIgFACIgDADIgEADIgJAPIgFAKIgGAKIgHAPIgEAHIgBAEIgCAEIgBAFIgCAFIAEgCIAEgCIAEgCIAEgBIAFgBIAEAAIAGgBIAEAAIAFAAIADgBIAGgBIAGgBIAFgCIAGgCIACgBIAAABIABgBIABAAIACgBIABAAIABgBIABAAIADgCIAEgBIAEgDIAFgCIAEgCIACgCIAFgDIADgEIABgCIACgFIACgFIABgFIAAgGIAAgGIgBgGIAAgEIgCgDIgCgCIgCgDIgEgDIgFgBIgFgBIgFgBIgGAAIgFAAIgGABgARjETIgEAAIgDgCIgDgBIgEgDIgDgCIgDgDIgDgEIgDgDQgOgggCgkIgCg3QgCgbAIgbQAJgcAVgUQAWgUAdgKIAEgCIAGAAQALAAAKACQALACAIAEQAHADAGAFIALAJIAGAHIAGAHIAJgTQAGgJAGgJIAKgLIALgLIAMgKIAFgCQAggNAeAPQAYALAQATQASAWAMAYQAQAeAIAhIAPBBIADATIAAAFIAAABIAAAFIgBAEIgBAFIgCAEIgCAEIgDAEIgCADIgEAEIgDADIgEACIgEACIgEACIgFABIgEABIgFAAIgFAAIgFgBIgEgBIgEgBIgLgIIgIgJIgEgIIgDgIIgCgMIgBgKIAAgDIgGgXQgDgLgCgLIgFgPIgEgQIgDgKIgGgLIgGgKIgHgJIgGgIIgEAFIgCAFIgDAFIgDAFQgGATgFAUQgDARgBASIgCAbIgBAUQAAAKgCAKQgDAKgGAIIgBADIgDACIgEADIgDACIgFACIgEACIgEABIgEAAIgFABIgGgBIgGgBIgDgBIgFgCIgDgCIgEgDIgEgDIgCgDIgDgDQgDgGgCgGIgEgJIgCgIIgCgIIgCgLIgBgMIgEgLIgCgLIgEgLIgEgLIgBgGIgFgIIgCgEIgCgEIgCgFIgEgFIgDgFIgCgDIgDgCIgDABIgEACIgFADIgBABIgDAFIgDAFIgCAFIgBAFIgCAFIgCAFIgBAGIgCAFIgCAfIgCAaQAAAMgBAMIgBASIABAQIAAAFIgCAEIgCAFIgCACIgCADIgEACIgEADIgGAAIgDAAgAFmEHQgKAAgKgDQgIgBgIgDIgQgHIgPgIIgPgJIgPgKIgLgIIgBgBIgDgCIADACIgEgDIgDgCIAAgBQgvgngYg5Qgag+AOhCQANhDAng5QAbgnAngdQAzgnBCgGIABAAQAggRAjgEQAmgFAlAIQAhAIAcATIADACIABADIACADIABADIABADIAAADIAAADIAAADIgBADIgBADIgCADIgBACIgDACIgDACIgDACIgEABIhMgGQgggDgfAKQgfAKgcASIg4AiQgXANgXAPIgDACIgEABIgCAAIgMATQgMAUgKAUQgJAVgEAXQgFAXABAYIABAGQAEARAGAQQAIAQAKAOQAIAMAKAKQALANAPAKIAeASIALAFIAGACIAFACIAHgBIAGgBIAFgCIAGgCIAHgCIAFgCIACgBIACgBIABAAIAHgDIABAAIAIgEIAKgFIAJgGIAKgFIAJgGIAEgFIAFgEIAAgGIAAgGIAAgGIAAgGIAAgGIABgFIAAgFIgTgBIgSgCIgRgBIgRgDQgHgBgIgDIgPgHIgFgCIgDgDIgFgDIgCgEIgDgEIgDgFIgCgGIgBgFIAAgGIAAgFIABgEIABgEIACgEIACgFIADgEIACgDIAFgEIADgCIAEgDIAFgCQAMgFAMgDQAKgCALAAIAXAAIAWACQAMABALADQAJADAKAEIAEACIAGgBIALgDIAMgDIALgDIAMgCIAIgCIAFAAIAFAAIAFAAIAEABIAFABIAEACIAFACIAEACIADAEIAEACIADAEIACAEIADAFIABAFIABAFIABAFIAAAFIgBAFIgBAFIgCAFIgDAEIgDAFIgCADIgEAEIgEADIgEACIgEACIgGACIgDABIgFABIgEAAIgFABIgEABIgFAAQACAggEAfQgCAggYAWQgVAUgcAOQgcANgcALQgdALgdAAIgDAAgAPeEDIgEAAIgGgBIgEAAQgMgBgMgEQgMgEgMgGQgLgGgJgIQgKgIgIgJQgIgIgGgJIgGgIIgDADIgCAEQgoAig1AFQg5AFggguQgUgegBgkQgCg4AhgtQAcgkArgPQAPgFAOAAIAGABIAGABIAFABQAWAJAUAQQARAPAPATQAOATAJAWIAVA5QAJAVAOAUIADAEIAEAEIAEAEIAEAEIAFAEIAEADIAFADIAEACIAGACIAFACIAFACIAGACIAFABIAFAAIAEAAIAEAAIADgBIAEABIADABIADACIAEACIACADIACAEIAAADIABAEIgBAEIgBAFIgDAEIgDADIgDACIgDADIgEADIgEACIgFACIgEACIgGABIgFABIgGAAIgHABIgBAAgAMNBAIgFADIgEADIgEADIgDADIgDAEIgEAEIgDAFIgCAEIgEAFIgCAFIgBAEIgBAFIgBAEIAAAFIgBAFIAAAFIAAAFIABAGIABAFIABAFIABABIABABIAFABIAFAAIAHgBIAFgCIAFgCIAGgCIAFgCIAFgCIAGgCIACgBIADgCIAFgDIAFgCIAGgDIAFgCIAFgBIAGAAIAFAAIgCgFIgCgFIgCgFIgDgFIgDgFIgCgFIgEgEIgCgFIgEgEIgEgEIgDgDIgEgEIgEgDIgFgEIgEgDIgFgDIgFADgAitD2IgFAAIgEgBIgFgBIgCAAIgGgBQgvgSgZgvQgYgtgDg0QgCgrACgpIgSgCIgogGQgKgBgIgEIgEgCIgDgDIgDgCIgCgCIgDgEIgCgDIgBgFIAAgEIAAgFIABgEIABgEIABgDIADgEIADgCIACgDIADgCIAEgCIAEgCIAEgBIAFgBIAFgBIAFgBIAFgBIA0gFIACAAIABgkQADgxANgvQACgIAEgGIADgEIAEgDIAEgDIAEgCIAFgBIAFgBIAEAAIAEACIAFACIADACIADAEIACADIACAEIABAGQAAApADAqIADAwIAVgBQAbgCAbACQAdADAKAaIACAEIABAFIABAGIAAAFIgBAFIgCAGIgBAFIgDAEIgCAFIgEAEIgDADIgFAEIgEACIgFACIgFABIgFABIgFABIgGAAIgFABIgFAAIgGAAIgpgCIgGgBIAAAHQACAjAFAiQADATAGASIACAFIADAFIADAFIADAEIADAFIAEAEIACADIALgFIAOgJIAHgFIAJgEIAJgFIAKgDIAEgBIAFgBIAEAAQAYABAPAUQALAOgCASQgBASgNALQgOANgQAKQgSALgTAJQgTAIgWABIgCAAgAo+DhIgFAAIgFgBIgDgCIgEgDIgDgDIgDgDIgEgEIgCgFIgCgFQgEgQgBgRQgBgTgDgSIgHghIgHgiIgCgOIAAgCIAAgEIAAAAIgCgRIgGgZIgGgSQgCgJgBgJQgBgIACgJIABgFIADgGQAEgLAJgIQAJgHAKgDQAJgCAJAAQAIAAAJADQAIADAIAGQAHAHAFAJQAFAIABAIIABAFIAAAHQAIgDAJgCQAfgGAfAEQAeAEAaAMQAHADAFAGIAFAEIACAEIADAFIACAFIACAEIABAGIAAAFIAAAGIgBAFIgCAFIgCAFIgDAFIgCAFIgFAEIgDADIgFADIgEADIgGADIgFABIgGABIgRgBIgRgDIgJgDIgLgDIgMgDQgJgCgIABIgGAAIgFABIgFABIgFACIgFADIgGADIAAAAIAAADIgCAwQAAAVgDAVQgDATgEATIAAAFIgBAFIAAAFIgBAEIgBAFIgDADIgCAEIgEACIgEADIgEABIgFAAgAwtC2QgggagOgqQgNgpADgrQAEgrAZgiQAbglArgGIAMgBQAmAEAiASQAkATAcAfQAXAZATAcQAWAfAaAcQAdAeAhAYIAcAUIAEADIABAEIACAFIAAAEIgBAFIgBAFIgDAEIgDADIgEADIgFABIgEABQgRgBgPgFQgRgFgQgIQgRgJgQgKQgPgJgPgMIgXgTIgBAFIgCAFIgDAEIgDAFIgRARIgTARQgJAIgKAGQgMAIgNAEQgNAEgPAAIgLABQgsgBgigcgAv4APIgDAFIgCAHIgCAGIgBAHIgBAFIAAAGIAAAFIAAAGIADALIADAGIABAGIACAGIACAFIADAFIADAFIAGACIAHACIAFAAIAEAAQAFgCAEgEIAJgIIAJgHIAJgHIALgGIAJgFIAFgCIAFgCIgJgJIgFgFIgFgEIgFgFIgEgEIgGgFIgJgGIgFgDIgFgDIgGgDIgEgCIgMgEIgFgBIgGgCIgFgBIgFAFgAznDRQgMAAgLgDQgMgDgLgFQgKgFgKgHIgJgGQghgggEguQgEgqADgrIADgsIgUgBIgkgBQgHAAgIgCIgEgCIgFgDIgEgDIgFgEIgDgEIgCgGIgBgFIgBgGIABgGIACgEIACgEIADgEQAMgLAPgHQASgHASgDQAPgDAQgCIABgoQACguAKgsQACgJAFgIIADgEIAEgDIADgDIAFgBIAEgCIAFAAIAEAAIAFAAIAEACIAEACIADAEIADADIADAEIABAEIABADIAAAEIAAAyIABBAIABASIAkAAIAhABIAFABIAFABQANAFAJAJQAJAJADAMQADAKgBAKQgCALgGAKQgHAKgKAGQgOAJgRACQgLABgKgBIghgEIACAxIADAsIABAGIACAHIACAGIACADIACADIAAABIAEACIAEABIAGABIAEAAIAGgBIAFgCIAFgCIAHgBIAHgBIAGABIAGABIAGACIAFACIAFADIADADIAFAEIADAEIADAFIADAFIACAFIABAGIABAFIAAAGIgBAFIgBAGIgBAFIgDAFIgDAFQgIALgMAHQgOAHgOADQgLADgLAAIgHgBgA8HDOIgHgCIgFgDIgFgEIgFgEIgEgEIgDgFIgCgFIgDgFIgCgFIgBgGIAAgFIAAgGIABgFIACgGIADgFIACgFIADgEIAEgEIAEgEIAFgDIAEgDIAGgDIAFgBIAGgBQASACASgEQAZgEAYgGQAXgGAWgJQAYgLAYgMIANgHQhUgLhFgvQg2gngChDQgBg0AngkQAwgrA9gSQBMgWBHAdIATAIIAEADIAEADIADAEIACAFIABAFIABAFIAAAFIgBAFIgBADIgCAEIgCAEIgEAEIgEACIgFADIgEABIgGABIgEAAIgFgBIgHgCIgGgCIgHgCIgGgCIgGgBIgGgCQgRgBgRACQgUACgTAGQgVAGgUAKQgRAIgPAMQgJAIgIAKIgEAFIgDAGIgBAEIgBAFIAAAEIAAADIACAIIACAFIADAEIADAFIADAEIAFAEIAEAEIAEAEQAVAOAXAIQAZAKAbAFQAbAEAbACQAZACAYAHQAKAEAIAHIAFAEIAFAFIADAEIAEAGIACAGIABAHIABAGIABAHIgBAHQgKAnghAZQghAZgmAUQgjATglANQgnAPgoAIQgSAEgSAAQgRAAgQgDg");
	this.shape_1.setTransform(183.65,27.7565);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("rgba(255,255,255,0.486)").s().p("AYdDIQgzhRAfhcQAMgjAagcQA5hBBVATQBAAPAOA/QAPBEg2AxQgcAZgjANQgfAKghgCQAVAoAtAHQAUAEASgLQAZgQATgXQANgPARgFQAMgEAGANQAHAQgOAOIAAABQgaAtgoAgQgUAPgYADIghACQhMgLgqhCgAZpAVQgQAdgLAgQAagLAdgBIAUgFQAWgIAJgVQAKgVgOgRQgFgGgHAAIgNgBQghAAgRAegARfETQgWgJgGgZQgOg1AAg2QAAgrAWgkQAbgrAygKQAKgCALACQAhAHAWAeQAUg5A4gOQAOgEAPADQAbAFAUAVQAvAxASBDQAMAtACAtQABATgPANQgVASgYgLQgbgMgCgfQgGhNgsg8QghBMgBBVQAAALgJAIQgeAbgegaQgLgKgDgQQgKg6gZg0QgFgJgGgGQgWALgEAaQgKBEgCBDQgBAIgHADQgGAEgHAAIgEAAgAFREEQhUgbgzhGQg8hRAShjQAShdA/hDQA/hBBZgPQAJgBAJgDQBkgmBYA6QAGAFAAAIQACARgPAGQg3gGg4ACQgiAEgbAPQg3Aeg1AiQgPAJgQAHQg6BEAIBYQACAbANAXQAoBCBKAQQAFABAGgCQAPgEAPgHQAggNAYgWIAAgjQgUgMgiADQgoAAgXggQgJgLACgOQAEgWATgKQAigRAmAEQAkAAAhAPQAogQArAEQAHACAGAEQATANgCAaQgBAVgSAMQgQAKgSABQgJAfAAAoQAAAIgDAHQgRAmgnAVQgwAZg0AOQgMACgMAAQgOAAgOgDgAPQECQhBgJgkg1IgGgJQgyA1hKgIQgngGgXgjQgjg3AVg/QAdhaBfgOQAIABAIADQA6AYAcA3QATAlANApQAPAqAmAXQAZAOAdgBIAGAEQAHAGgCAMQgEALgJAGQgTAMgWAAIgGABQgFAAgEgCgALnCOQABAFADAGIALACIBRgbQgPgrgmgYQgwAaAFA3gAi+D0QhBgXgWhBQgahPAJhQQgqgCgigMQgJgDgGgJQgHgMAGgMQAKgUAYgCIAJgCIA0gFQAEhFAVhGQAGgVAYAAQAPADABAOQAEAsADAtIADAwQA0gKAtAXQAKAFAFALQAHANgFAQQgNAjgngBQgbAAgfgDQgFBLAjA+IADAEQANACAPgMQAngiAnAcQAQAMAAATQAAAqgpAUQgXAMgZAJQgQAGgQAAQgJAAgJgCgApiC3QgEhDgNhFIgShUQgEgTAOgRQAcgjAnAWQAbAQABAfQBTgZBDAxQAGAEACAIQALAjgfAUQgZAPgcgMQgkgNgjAKIgLAFQAABPgRBLQgCAJgJAEIgJABQghgHgDgjgAxRCGQgthfA4hVQAOgWAZgLQA5gYA3AjQBRAyA3BPQAWAgAdAbQAcAbAhAXQALAYgZAHQgKADgJgDQhNgUg6g2QgeA4g7AVQgUAGgTABQhPgFgjhIgAv9BQQAFAOAHAMIAXAEIA9gpQAEgIgRgOQgRgOgSgKQgSgKgVgDQgWAgANAmgA8HDOQgsgRAMgvQADgLAHgIQATgVAdgCQAVAFAWgDQBFgPA9gkQhvgLhIhSQgKgLgGgOQgYg+Alg0QARgYAWgQQBIgzBYACQA2ABArAeQAJAGgBAKQgEApgngNQgqgOgsAJQhBAOgrAwQgVAYAVAYQAZAcAiAMQA0ARA3ABQAuABAdAeQAJAIADAOQAGAZgQAVQgnA4g/AdQhAAfhEASQgbAIgbAAQgSAAgRgDgA0yC0QggghgEgtQgGhBAHhAQgpAEgmgPQgQgHABgSQABgUARgJQAmgWArgBQgBhLAXhIQACgGAIgDQAegMAGAfQAEAaABAbIACBSQApgDAmAIQAQAFAJANQAXAigdAeQgNAOgSAEQgfAEgfgHQgDA7APA4IACAEQAUAIAWgIQANgFAPAJQAjAWgOAnQgGASgSAJQgdANgaAAQgoAAgkgdg");
	this.shape_2.setTransform(183.6909,27.7768);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1}]}).to({state:[{t:this.shape_2}]},24).wait(25));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-7.8,-8.2,379.40000000000003,76.60000000000001);


(lib.Start = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.StartGame();
	this.instance.setTransform(183.7,27.8,1,1,0,0,0,183.7,27.8);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AuUG+IgFgBIgGgCIgFgCIgFgCIgFgDIgEgDIgFgEIgDgFIgDgFIgFgKQgCgFAAgFQgCgIACgIQABgIADgHQAEgHAFgGIAIgHIAFgDIAHgEIAGgDIABgEIACgEIguAQIgrAPIgpAMQgQAFgSACIgMACIhMAZQghALgiAJQgaAHgaAEQgWAEgXgGQgMgDgJgHIgEgEIgIgKIgGgKIgEgLIgCgMIAAgGIAAgGIACgGIADgFIACgGIAEgFIADgFIAEgEQAdgZAkgNIBJgcIAzgVIA+gWIAXgJIgaAEQgLABgMAAQgKABgLgCQgMgCgJgFQgLgFgGgJIgIgKIgDgGIgDgFIhXAdIhNAYQgdAKgdAIQghAJggAFQgNACgNgBIgGgCIgHgCIgGgCIgGgDIgGgEIgEgEIgFgFIgSAFIgWAFIgWADIgVACQgKAAgKgDIgHgCIgGgDIgFgEIgFgEIgEgFIgEgFIgDgFIgCgGIgDgGIgBgGIAAgGIAAgGIABgGIhXAgIhMAaIg5ATQgeAKgfAGQgXAFgXgHIgEgCIgEgDIgEgDIgEgDIgCgEIgDgEIgDgEIgCgEIgBgFIgBgEIgBgFIAAgFIAAgFIABgEIABgFIABgFIADgEIAEgGIAEgGIAEgFQAMgKAOgGIAegOIAlgQIAdgMIgFgFIgEgEIgDgFIgDgGIgCgFIgCgGIAAgGIAAgGIACgGIACgFIADgGIACgFIAEgFIAEgFIAFgEIAFgDIAGgEIgGABIgFAAIgGAAIgGAAIgFgBIgGgCIgFgDIgFgDIgEgEIgFgFIgDgFIgDgGIgBgGIgBgHIAAgGIABgGIACgFIADgFIACgFQAJgNAPgIIAggQIAsgSIAmgQIAZgKIgEgEIgGgFIgDgGIgDgEIgBgGIgCgFIAAgGIAAgGIACgFIACgFIACgEIgEgFIgCgFIgCgFIgBgGIAAgGIAAgFIACgGIACgFIADgFIAEgFQAJgIALgFIAYgJIAdgMIAfgLIAHgDIgDgEIgDgFIgCgGIgBgGIABgFIABgGIADgFIADgFIAEgEIAEgDQATgKAUgFIA0gNIAvgNIAmgJIAXgEIA5gTIA7gUIAqgPIAhgKIANgDIAGgBIAFABIAGABIAEACIAFADIADADIADADIADAEIADAFIABAEIABAFIAAAFIgBAFIgBAFIgCAFIgEAEIgDAEIABAHIABAHIBDgXIA7gTIA0gQIAqgNQAMgEANAAIAGABIAHACIAFACIAFACIAEADIAEAEIADADIAEAFIACAEIABAGIABAFIABAFIAAAGIgBAFIgBAGIgDAFIgDAEIgEAEIgFAEIgEADIgGAEIgEADIAUgFIAegIIAfgGIASgDIAKgBIAHABIAHABIAGABIAFADIAEADIAEAEIAEAEIADAEIADAFIABAFIACAHIAAAGIAAAGIgBAHIgCAFIAmgKIAmgLQASgFATgEIAYgDIAEAAIAGABIAFABIAFADIAFACIAEAEIAEADIAEAFIACAEIACAFIACAFIABAHIABAGIAAAGIgBAHQA3gNBBgTQAxgOAygMIBsgZIBYgSQAegGAcAFIAGACIAEADIAFADIAEADIAFAEIADAEIAEAFIACAGIACAFIABAFIABAFIAAAGIgBAFIgBAGIgCAFIgCAEIgEAFIgEAGIgFAFIgEAEIgGAEIgFAEIgGADIBngXIBUgSIBLgNIBSgPQATgDARABIAGABIAGACIAFACIAGADQBUgRBUgQIB/gYQA/gMBAgJIB/gTIBQgKIAGAAIAGABIAHACIAFADIAFAEIAFAEIAEAEIADAGIAEAFIACAGIABAHIAAAGIAAAGIgBAFIgBAEIgCAFIgDAFIgDAFIgEAEIgEAEIgFADIgFADIgFACIB5gXIBYgQIBXgPIBOgNQAVgEAVAAIAFABIAFACIAFACIAFACIAEADIAEAEIAEAEIADAEIADAEIACAFIACAFIABAGIAAAGIAAAGIAFAAIAGAAIAGAAIAHAAIAGABIAFABIAGABIAGADIAFADIAFAEIAEAEIAFAFIADAFIADAGIACAGQA4gGA+gNQArgJArgHIBXgOIBSgLIAzgGIAGABIAGABIAHABIAGACIAGADIAGAEIAFAFIAEAEIADAFIADAFIACAFIACAGIABAGIAAAGIAAAGIgBAFIgBAGIgDAFIgDAFIgCAEQgrAgg5AEQgjACgkAFIhgAPIhgAPQgnAGgmAIIAJAAIAIAAIAHABIAGABIAHABIAGACIAHADIAFADIAGADIAEAEIAFAFIADAFIAEAFIACAGIAOgCIAPgDIAPgCIAOgCIAIgBIAHABIAHABIAGACIAGADIAFADIAFAEIAFAEIADAFIA2gIIA0gHIArgGQANgCANADQALACAKAHIADAEIAFAEIADAEIADAFIADAFIABAGIACAHIAAAHIAAAHIgCAHIAHgBIAHgBIAHgBIAHgBIgHABIAogFIAngEIAjgEQARgCASADIAGABIAGACIAGADIAFAEIAGAEIAEAFIAEAGIACAGIADAGIABAHIABAGIgBAHIgBAHIgDAGIgCAGIgEAFIgEAFIgGAFIgFAEIgGADIgGACIgHABIACAGIABAFIABAGIAIgBIAHgBIAHgBIAGAAIAGABIAGACIAGADIAGADIAFAEIAFAEIADAEIAEAFIACAEIACAFIACAFIACAIIABAHIgBAIIgCAHIgBAGIgCAGIgDAFIgEAFQgPAPgVAJQgYAKgYALIgqAVIgkARIgVAKIAAABIgEAFIgEAFQgHAHgIAFQgIAFgKADIgSAGIgTAFIgMACIgBAAIgFACIgEACIgFABIgEABIgHAAIgGAAIgGgBIgHgCIgGgDIgFgDIgPADIgPADIgMAEIgMADIgHACQgJAEgJABIgQACIgVAFIgWAEIgHABIgGgBIgHAAIgFgCIgGgCIgFgDIgFgDIgFgEIgEgFIgEgFIgDgFIgCgGIgDgGIgCgGIgBgGIAAgGIhWAQQgmAHgnAFIg8AHQgjAEgiAAQgTAAgSgFIgFgCIgFgDIgFgEIgEgEIgEgFIgDgFIgDgFIgCgGIgCgGIAAgGIiyAmIiFAdIiDAdIh9AbQgmAHglgBIgHgBIgHgCIgGgEIgFgDIgFgEIgEgFIgFgFIgCgGIgDgFIg1AQIg1ASIgtAPQgLAEgNABIgGABIgGgBIgGgBIgFgBIgGgCIgFgDIgFgEIgEgDIgEgEIgDgFIgEgFIgCgFIgCgFIgBgHIhLATQglAJglAHIgwAJQgZAEgYABQgUABgSgJIgaADIgeADQgPAAgOgBIgZgEQgIgCgIgDIgDgCIgFgDIgEgDIgFgEIgDgEIgEgEIgDgFQhTAUhVAXIiGAkQhCAShCAPQg7AOg7AKQgkAHgmACIgVAIIgWAHIgWAHIgOAEIgHAAIgGAAgAttGzIAAABIABgBIABAAIgBAAIgBAAgA7fgMIABAAIgBAAg");
	this.shape.setTransform(177.45,34.175);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("EgiIAFYIgGgBIgEgBIgFgDIgEgCIgEgEIgDgDIgCgEIgDgFIgCgFIgBgFIAAgFIAAgFIABgFIACgEIACgEIACgDQAOgPASgLIAxgaQASgKASgIIAggOIAogNIAEAAIAEABIAEABIAEABIAEACIADADIADADIADAEIABAEIACAEIAAAFIAAAEIgBAFIgBAEIgCAEIgDAEIgEADQgPALgTAKQgTAKgUAMIgkAXIgeAUIgYAQIgFABIgFABIgFABIgFgBgEAihAEpIgGAAIgFgBIgGgCIgFgCIgWgMIgVgMIgVgMIgXgQIgWgPQgHgGgGgJIgCgDIgBgFIgBgEIAAgFIAAgEIABgFIACgEIABgEIADgDIADgEIADgDIADgCIAFgCIAEgBIAGgCIAFAAIAFABQALABALAFIAVAJIAUAJIAbANIAcANIAPAIIADADIADACIADAEIACADIACADIABAEIACAEIABAEIABAEIAAAEIAAAEIgBAEIAAAEIgCAEIgCADIgBAEIgCAEIgDAEIgEADIgDADIgFACIgDACIgFABIgEABIgFABIgEAAgEgjHAAgIgFgBIgEgBIgEgCIgDgDIgEgDIgDgDIgCgEIgCgEIgCgEIgBgFIAAgFIAAgFIADgFIACgFIACgEIADgDIAEgDIADgDIAEgCIAEgBIAlgFIAfgCQASgCAUABIATAAIATACIAFACIADABIADADIAEACIADAEIACAFIADAEIABAFIAAAFIAAAGIgCAEIgCAFIgDAEIgDAEIgFADIgEADIgFABQgPACgQAAIgWABQgOAAgPABIgZADIgXAEIgFAAIgEAAgEAhRgAVIgKgBIgFgCIgEgCIgFgDIgDgEIgDgEIgDgDIgCgEIgBgEIgBgFIAAgFIAAgFIABgEIABgEIACgEIADgEIADgEIADgDIAFgDIADgCIAYgHIAfgHIAfgGIAegEIALgBIAGABIAGACIAFACIAEADIADADIADADIAEAEIACAEIACAEIABAFIACAGIAAAFIAAAGIgCAGIgBAFIgDAFIgCAEIgFAFIgDAEIgFADIgFACIgGACIgfAFIghAEIgdADIgKAAIgOgBgA/Zi2IgCAAIgDgBIgcgEIgcgEIgbgGIgbgGIgYgFIgKgCIgFgBIgEgCIgEgDIgDgDIgEgEIgCgDIgCgEIgBgFIgBgFIgBgEIABgFIABgFIABgDIABgEIACgDIADgDIACgDIADgCIADgCIADgCIADgBIAEgCIADAAIAEgBIAEAAQAOACAOAFIAZAJIAYALIAZAKQAOAFAPAEQALADAKAFIADACIACADIADADIACAEIABAFIAAAFIgBAEIgBAEIgDAEIgCADIgDACIgDACIgEACIgDABIgFAAgAfyj1IgIgBIgEgBIgEgCIgEgDIgDgDIgDgDIgDgEIgCgEIgBgEIAAgFIgBgEIAAgEIABgFIABgEIACgEIADgDIADgDIABgCIgBAAIAKgHIANgIIAOgHIAQgHQAKgFALgEIAFgBIAEgBIAFAAIAEABIAFABIAEACIAFACIADACIADADIAEADIACAEIACAEIADAEIABAEIABAFIABAEIgBAFIAAAEIgBAFIgCAEIgCAEIgDAEIgDAEIgEADIgDACIgEADIgSAHIgUAHIgVAGQgIACgHAAIgGAAg");
	this.shape_1.setTransform(183.15,33.475);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape_1}]},1).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-44.6,-10.4,455.6,89.2);


// stage content:
(lib.Website = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [0,1];
	// timeline functions:
	this.frame_0 = function() {
		/* Stop at This Frame
		The  timeline will stop/pause at the frame where you insert this code.
		Can also be used to stop/pause the timeline of movieclips.
		*/
		
		this.stop();
		
		
		/* Click to Go to Frame and Stop
		Clicking on the specified symbol instance moves the playhead to the specified frame in the timeline and stops the movie.
		Can be used on the main timeline or on movie clip timelines.
		
		Instructions:
		1. Replace the number 5 in the code below with the frame number you would like the playhead to move to when the symbol instance is clicked.
		2.Frame numbers in EaselJS start at 0 instead of 1
		*/
		
		
		this.Button0.addEventListener("click", fl_ClickToGoToAndStopAtFrame_2.bind(this));
		
		function fl_ClickToGoToAndStopAtFrame_2()
		{
			this.gotoAndStop(2);
		}
	}
	this.frame_1 = function() {
		/* Stop at This Frame
		The  timeline will stop/pause at the frame where you insert this code.
		Can also be used to stop/pause the timeline of movieclips.
		*/
		
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1).call(this.frame_1).wait(1));

	// Buttons
	this.Button0 = new lib.Start();
	this.Button0.name = "Button0";
	this.Button0.setTransform(960.05,774,1,1,0,0,0,183.7,27.8);
	new cjs.ButtonHelper(this.Button0, 0, 1, 2);

	this.timeline.addTween(cjs.Tween.get(this.Button0).to({_off:true},1).wait(1));

	// Layer_2
	this.instance = new lib.Symbol2();
	this.instance.setTransform(785.6,358.75,1,1,0,0,0,158.4,66.8);

	this.text = new cjs.Text("Midnight\nForever\nStream", "bold 96px 'FOT-Rowdy Std EB'", "#FFFFFF");
	this.text.lineHeight = 126;
	this.text.parent = this;
	this.text.setTransform(723.5,352.1);
	this.text.shadow = new cjs.Shadow("rgba(0,0,0,1)",0,0,9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.text},{t:this.instance}]}).to({state:[]},1).wait(1));

	// Layer_1
	this.instance_1 = new lib.Symbol1();
	this.instance_1.setTransform(961.65,541.5,1.5,1.5,0,0,0,641.1,361);
	this.instance_1._off = true;
	var instance_1Filter_1 = new cjs.ColorFilter(1,1,1,1,0,0,0,0);
	this.instance_1.filters = [instance_1Filter_1];
	this.instance_1.cache(-2,-2,1284,724);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1).to({_off:false},0).wait(1));
	this.timeline.addTween(cjs.Tween.get(instance_1Filter_1).wait(1).to(new cjs.ColorFilter(0.5,0.5,0.5,1,127.5,127.5,127.5,0), 0).wait(1));

	this.filterCacheList = [];
	this.filterCacheList.push({instance: this.instance_1, startFrame:1, endFrame:1, x:-2, y:-2, w:1284, h:724});
	this.filterCacheList.push({instance: this.instance_1, startFrame:0, endFrame:0, x:-2, y:-2, w:1284, h:724});
	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(960,540,960,540);
// library properties:
lib.properties = {
	id: '232646D6040DBD43B36005740AE51382',
	width: 1920,
	height: 1080,
	fps: 24,
	color: "#000033",
	opacity: 1.00,
	manifest: [
		{src:"images/Website_atlas_1.png", id:"Website_atlas_1"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['232646D6040DBD43B36005740AE51382'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;